#!/bin/bash

((!$#)) && echo No repo name, command ignored! && exit 1
repo_name=${1}
local_name=${2}

git exist-clone $repo_name $local_name

git exist-clone PythonTemplate temp
cp -a temp/logging $repo_name
cp temp/{.gitignore,LICENSE,main.py} $repo_name
rm -rf temp

cd $repo_name
echo "# $repo_name" > README.md

git add .;
git commit -m "first commit";
git push -u origin master

echo ""
echo "Python virtual enviroment initialising..."
python -m venv venv
