#!/bin/bash

((!$#)) && echo No repo name, command ignored! && exit 1

git clone https://github.com/marmstr93ng/$1.git

cd $1

echo ""
echo "Python virtual enviroment initialising..."
python -m venv venv

git install-req
