#!/bin/bash

((!$#)) && echo No commit comment, command ignored! && exit 1

source "$(git --exec-path)/git-sh-setup"

cd venv/scripts

source activate
cd ../..
pip freeze > requirements.txt

git status

while true; do
    read -p "Do you wish to add, commit and push changes?" yn
    case $yn in
        [Yy]* ) git add .; git commit -m "$1"; git push; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
