#!/bin/bash

((!$#)) && echo No repo name, command ignored! && exit 1
repo_name=${1}
local_name=${2}

git exist-clone $repo_name $local_name

cd $repo_name

echo ""
echo "Python virtual enviroment initialising..."
python -m venv venv

git install-req
